// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zogtdopskjdutygoobgc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpvZ3Rkb3Bza2pkdXR5Z29vYmdjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzNzc5OTEsImV4cCI6MjA3MTk1Mzk5MX0.pevlnD0H4OBK_emm_WkXRX_Gbikv8ipYdr8eyP1r7E4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});